# file: .github/workflows/python-ci.yml
# 定義這個 workflow 的名稱，會顯示在 GitHub Actions 頁面上。
name: Python CI
# 作用：指定 workflow 觸發的事件。目前監控 push 和 pull_request 事件
on:
  # 當執行push到該分支時觸發
  push:
    branches: [ main ]
  # 當執行 pull_request 到該分支時觸發
  pull_request:
    branches: [ main ]
# 當被觸發時，執行以下的 jobs
jobs:
  # 作用：定義一個 job，名字叫 build-and-test。
  build-and-test:
    # 作用：指定執行環境
    runs-on: ubuntu-latest
    # 作用：定義這個 job 需要執行的步驟
    steps:
      # 步驟名稱:確認代碼庫內容
      - name: Checkout code 
      # 使用官方 action 取得 repo 內容到 runner
        uses: actions/checkout@v3
      # 步驟名稱:設定 Python 環境
      - name: Set up Python
        # 使用官方 action 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          # 作用：指定 Python 的版本
          python-version: "3.11"
      # 步驟名稱:安裝依賴
      - name: Install dependencies
      # 執行多行 shell 指令。
      # 更新 pip 並安裝 requirements.txt 中的依賴。
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # 步驟名稱:執行測試
      - name: Run tests
      # 執行測試指令。
        run: |
          pytest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
